# Generated by Django 5.1.3 on 2024-11-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='products.supplier'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.TextField(),
        ),
    ]
