# Generated by Django 5.1.3 on 2024-11-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total_price_orderproduct_total_price_orderitem'),
        ('products', '0003_supplier_contact_info_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
