# Generated by Django 5.1.3 on 2024-11-26 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_supplier_alter_orderitem_total_price'),
        ('products', '0004_product_attributes_alter_product_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
            preserve_default=False,
        ),
    ]
