# Generated by Django 5.1.3 on 2024-11-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderproduct_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='total_price',
        ),
    ]
